import { mkdir, readFile, writeFile, copyFile, readdir, unlink } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const out = resolve(root, 'dist');
await mkdir(out, { recursive: true });
// Only the portfolio's public assets are published. Admin HTML is served after authentication.
for (const name of ['certificates.css', 'certificates.js', 'admin.js', 'owner-login.js', 'resume.js']) {
  await copyFile(resolve(root, 'public', name), resolve(out, name));
}
for (const name of await readdir(out)) {
  if (['admin.html', 'admin'].includes(name)) await unlink(resolve(out, name));
}
let index = await readFile(resolve(root, 'public/index.html'), 'utf8');
index = index.replace(/<div class="honors-footer"><a class="honors-owner"[^>]*>.*?<\/a><\/div>/g, '');
index = index.replace('const resumeUrl = safeUrl(CONFIG.resumeUrl, true);', 'let resumeUrl = safeUrl(CONFIG.resumeUrl, true);\nwindow.addEventListener("portfolio:resume", event => { resumeUrl = event.detail.url || ""; });');
index = index.replace('</body>', '<script src="/resume.js" defer></script></body>');
await writeFile(resolve(out, 'index.html'), index);
const admin = await readFile(resolve(root, 'public/admin.html'), 'utf8');
const loginAt = admin.indexOf('<section id="login-panel"');
const studioAt = admin.indexOf('<div id="studio"');
const footerAt = admin.indexOf('<p class="notice"');
if (loginAt < 0 || studioAt <= loginAt || footerAt <= studioAt) throw new Error('Admin template boundaries invalid');
const loginHTML = (admin.slice(0, studioAt) + admin.slice(footerAt)).replace('/admin.js', '/owner-login.js');
const studioHTML = (admin.slice(0, loginAt) + admin.slice(studioAt)).replace('id="studio" hidden', 'id="studio"');
await writeFile(resolve(root, 'netlify/lib/studio-pages.mjs'), `// Generated by scripts/build.mjs\nexport const loginHTML = ${JSON.stringify(loginHTML)};\nexport const studioHTML = ${JSON.stringify(studioHTML)};\n`);
console.log('Built public portfolio and authenticated owner studio.');
